### ISSUE TITLE
TS definitions for `@graphile/supporter`

### ISSUE THREAD

**Issue by marshall007** [graphile/issues#2]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

It would be nice if the `@graphile/supporter` plugin shipped with TypeScript definitions, including a module augmentation on `PostGraphileOptions` to include _Pro_ plugin options.

I think the declaration file would need to look something like this:

```ts
// index.d.ts

import { PostGraphilePlugin } from 'postgraphile';

declare const plugin: PostGraphilePlugin;
export default plugin;

declare module 'postgraphile' {
  export interface PostGraphileOptions {
    simpleSubscriptions?: boolean;
    readOnlyConnection?: boolean;
    defaultPaginationLimit?: number;
    graphqlDepthLimit?: number;
    graphqlCostLimit?: number;
    exposeGraphQLCost?: boolean;
  }
}
```

**Comment by benjie** [comment]
Closing this, since this is all open source now and has type definitions 👍
