### ISSUE TITLE
Allow specifying the cost limits per request

### ISSUE THREAD

**Issue by deinspanjer** [graphile/issues#3]
We would like to allow different cost limits for different tiers of users.
Right now, the setting is a validation rule, so we can't dynamically change it.

**Comment by benjie** [comment]
`@graphile/pro@0.8.0` is now out which introduces the ability to override limits on a per-request basis: 

https://www.npmjs.com/package/@graphile/pro#overriding-limits-on-a-pre-request-basis

Let me know how you get on!

**Comment by deinspanjer** [comment]
I've done some initial testing with this and it seems to fit the bill perfectly!  Will let you know when it is released

**Comment by benjie** [comment]
Great, thanks for letting me know 🙌
