### ISSUE TITLE
peerDependency on postgraphile missing in @graphile/pro

### ISSUE THREAD

**Issue by crubier** [graphile/issues#6]
### Summary

v1.0.0, does not declare postgraphile as a peerDependency in package.json, but it does import postgraphile at some point. 

Importing a package that is not declared as a dep or peerDeep is not good, and yarn v2 is especially strict about that. 

I had to use the workaround of adding these lines to my .yarnrc/yml

```
packageExtensions:
  "@graphile/pro@*":
    peerDependencies:
      postgraphile: "*"
```

Easy fix is to just add postgraphile as a peerDep in package json

### Steps to reproduce

Use yarn v2 to install a server with postgraphile + @graphile/pro

### Expected results

Works

### Actual results

Yarn complains that @graphile/pro tries to import postgraphile without defining it in dependencies

### Possible Solution

Add this to package.json of @graphile/pro

```
    "peerDependencies": {
      "postgraphile": "*"
     }
```

**Comment by benjie** [comment]
Thanks for the report; resolved in v1.0.1 :+1:
